### ISSUE TITLE
交集选择器和并集选择器

### ISSUE THREAD

**Issue by GRPdream** [GRPdream/My-front-end#15]
## 交集选择器
如字面意思，将两个或多个选择器的值放在一起取其交集
试例 html 页面：
```html
<div id="app" >
    <h1>我是'app'盒子的 h1</h1>
    <div class="mydiv">
      <h1>我是'mydiv'盒子的 h1</h1>
    </div>
  </div>
```
未加样式时的样子
![图片](https://user-images.githubusercontent.com/32740073/56857802-50a42b00-69a4-11e9-8486-16a738555b3c.png)

现在使用交集选择器给第二个盒子的 `h1` 加上样式
```css
.mydiv h1{
      color: red;
    }
```

加上样式的样子
![图片](https://user-images.githubusercontent.com/32740073/56857841-b395c200-69a4-11e9-964b-f21b7c8066a3.png)

可以看到，精准的为第二个 `h1` 加上了样式

## 并集选择器 
继续使用上面的列子，这次为所有字体加上 `font-size` 属性
```css
#app,h1,.mydiv{
      font-size: 25px;
    }
```

效果：
![图片](https://user-images.githubusercontent.com/32740073/56857891-3585eb00-69a5-11e9-8098-8cdcdc4bcd0b.png)
![图片](https://user-images.githubusercontent.com/32740073/56857892-3f0f5300-69a5-11e9-9b4a-d962aeab8422.png)
